[[buildpacks]]
id = "io.buildpacks.java"
name = "Java Buildpack"
version = "0.0.9"

[[buildpacks.order]]
group = [
  { id = "io.buildpacks.jvm", version = "latest" },
  { id = "io.buildpacks.maven", version = "latest" },
  { id = "io.buildpacks.tomcat", version = "latest", optional = true }
]

[[buildpacks.order]]
group = [
  { id = "io.buildpacks.jvm", version = "latest" },
  { id = "io.buildpacks.gradle", version = "latest" },
  { id = "io.buildpacks.tomcat", version = "latest", optional = true }
]