[[buildpacks]]
id = "io.buildpacks.react"
name = "React Buildpack"
version = "0.0.9"
path = "react-buildpack"

[[buildpacks.order]]
group = [
  { id = "io.buildpacks.nodejs", version = "latest" },
  { id = "io.buildpacks.react", version = "latest" }
]
